name: CI
on:
  pull_request:
    branches: [develop]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code under repository
        uses: actions/checkout@v2
      - name: Use nodeJS
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: Install dependencies
        run: npm install
      - name: Check code formatting
        run: npm run format:check
      - name: Run test
        run: npm run test -- --coverage
        env:
          CI: true
