name: CI
on:
  pull_request:
    branches: [develop]
  push:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code under repository
        uses: actions/checkout@v2
      - name: Use nodeJS
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: Install dependencies
        run: npm install
      - name: Check code formatting
        run: npm run format:check
      - name: Run test
        run: npm run test -- --coverage
        env:
          CI: true
      - name: Build project
        if: github.event_name == 'push'
        run: npm run build
      - name: Install surge
        if: github.event_name == 'push'
        run: npm install -g surge
      - name: Deploy to Staging
        if: github.event_name == 'push'
        run: surge --project ./build --domain enormous-sugar.surge.sh/
        env:
          SURGE_LOGIN: ${{ secrets.SURGE_LOGIN }}
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
